import type { Metadata } from 'next'
import './globals.css'
import React from 'react'
import PrivyWalletProvider from '@/providers/PrivyWalletProvider'

export const metadata: Metadata = {
  title: 'TerraPulse',
  description: 'Generated by create-solana-dapp',
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`antialiased`}>
        <PrivyWalletProvider>{children}</PrivyWalletProvider>
      </body>
    </html>
  )
}
// Patch BigInt so we can log it using JSON.stringify without any errors
declare global {
  interface BigInt {
    toJSON(): string
  }
}

BigInt.prototype.toJSON = function () {
  return this.toString()
}
