[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
terrapulse = "EeLVcxJ4sG9Gj5bqsKbUG25KMsGrLSWcauKQwBUpCWRh"

[programs.localnet]
terrapulse = "EeLVcxJ4sG9Gj5bqsKbUG25KMsGrLSWcauKQwBUpCWRh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
